type: object
additionalProperties: false
properties:
  meta:
    $ref: '#/$defs/settingsMetas'
  identifier:
    type: string
  $uid:
    type: string
  title:
    type: string
  version:
    type: string
  notes:
    type: string
  style:
    type: array
    items:
      type: string
      enum:
      - theme-grid
      - pages
      - no-text-transform
  submission_url:
    type: string
  'form_typename':
    type: string
  'url':
    type: string
  'form_name':
    type: string
  'formid':
    type: string
  'form_version':
    type: string
  'form id':
    type: string
  'form_idv10':
    type: string
  'form_ID':
    type: string
  'from_title':
    type: string
  'default_langauge':
    type: string
  'id':
    type: string
  'language':
    type: string
  'default':
    type: string
  'id_name':
    type: string
  'id_title':
    type: string
  'paper_version':
    type: string
  'First_form':
    type: string
  'allow_import':
    type: string
