type: object
additionalProperties: false
properties:
  metas:
    $ref: '#/$defs/settingsMetas'
  identifier:
    type: string
  # $uid:
  #   type: string
  title:
    type: string
  root:
    type: string
  namespaces:
    type: object
  version:
    type: string
  delimiter:
    type: string
  prefix:
    type: string
  auto_send:
    type: boolean
  auto_delete:
    type: boolean

  instance_name:
    type: string
  public_key:
    anyOf:
    - type: string
      pattern: "^[^\n]+$"
    - type: 'object'
      properties:
        '$ref':
          type: 'string'
  notes:
    type: string
  style:
    type: array
    items:
      type: string
      enum:
      - theme-grid
      - pages
      - no-text-transform
  submission_url:
    $ref: '#/$defs/type--url'
  # 'form_typename':
  #   type: string
  # 'url':
  #   type: string
  # 'form_name':
  #   type: string
  # 'formid':
  #   type: string
  # 'form_version':
  #   type: string
  # 'form id':
  #   type: string
  # 'form_idv10':
  #   type: string
  # 'form_ID':
  #   type: string
  # 'from_title':
  #   type: string
  # 'default_langauge':
  #   type: string
  # 'id':
  #   type: string
  # 'language':
  #   type: string
  # 'default':
  #   type: string
  # 'id_name':
  #   type: string
  # 'id_title':
  #   type: string
  # 'paper_version':
  #   type: string
  # 'First_form':
  #   type: string
  # 'allow_import':
  #   type: string
