---
type: object
additionalProperties: false
$schema: "http://json-schema.org/draft-07/schema#"
$id: "https://dorey.github.io/a1d05eba1/schema.json"
properties:
  schema:
    type: string
  survey:
    "$ref": "#/$defs/survey"
  translations:
    "$ref": "#/$defs/translations"
  choices:
    "$ref": "#/$defs/choices"
  settings:
    "$ref": "#/$defs/settings"
  metas:
    "$ref": "#/$defs/metas"

  # information about the deployent. e.g. timestamp? Or should this go
  # in settings?
  deployment:
    type: object
